services:
  - type: web
    name: pixelstreaming-websocket
    env: node
    buildCommand: npm install
    startCommand: node server-example.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001

